vim/vimeo/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'vimeo.views.home', name='home'),
    # url(r'^vimeo/', include('vimeo.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^searching/$','userbase.views.filt'),
    url(r'^display/$','userbase.views.display'),
                       
    url(r'^pay/(\w+)/$','userbase.views.filt_pay'),
    url(r'^vid/(?P<queries>\w+)/$','userbase.views.filt_vid'),
    url(r'^sp/(?P<queries>\w+)/$','userbase.views.filt_sp'),
                       

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
    
    
)

vim/userbase/models.py
from django.db import models

class user_data(models.Model):
    username = models.CharField(max_length = 100)
    url = models.URLField()
    payment = models.CharField(max_length = 10)
    videos = models.CharField(max_length = 10)
    staff_pick = models.CharField(max_length = 10)

    class Meta:
        app_label = 'userbase'

    def __unicode__(self):
        return self.username
    
    
class sqf(models.Model):
    searq = models.CharField(max_length=100,blank = True,null=True,)

vim/userbase/forms.py
from django import forms
from userbase.models import sqf

class sq(forms.Form):
    searq = forms.CharField()
    

vim/userbase/views.py
import csv
from userbase.models import user_data 
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from userbase.forms import sq

def data_entry():
    inp = open('result1.csv', 'rb')
    reader = csv.reader(inp, delimiter=',')
    j = 0
    print reader
    for row in reader:
        database = user_data(username = str(row[0]), url = str(row[1]), payment = str(row[2]),videos =str(row[3]) ,staff_pick=str(row[4]))
        database.save()
        
        print j
        j = j+1

    inp.close()

def display(request):
    result = user_data.objects.all()
    form = sq()
    context ={'result': result,'form':form,}
    return render_to_response('display.html',context,context_instance= RequestContext(request))


def filt(request):
    if request.method == 'POST':
        form = sq(request.POST)
        if form.is_valid():
	    queries = form.cleaned_data['searq']
	    if len(queries) ==0:
	        result = user_data.objects.all()
	        context = {'result':result,}
	        return render_to_response('display.html',context,context_instance = RequestContext(request))
	    else:
                length = len(queries)
	        result = user_data.objects.filter(username__icontains=str(queries))
	        context = {'result':result,'form':form,'query':queries,}
	        return render_to_response('display.html',context,context_instance=RequestContext(request))
	else:
	    result = user_data.objects.all()
            form = sq()
            context = {'result':result,'form':form,}
	    return render_to_response('error.html',context,context_instance=RequestContext(request))
    else:
	result = user_data.objects.all()
	form = sq()
	context = {'result':result,'form':form,}
	return render_to_response('display.html',context,context_instance=RequestContext(request))

def filt_pay(request,queries):
    result = user_data.objects.filter(username__icontains=str(queries),payment__icontains = 'YES')
    form = sq()
    context = {'result':result,'form':form,'query':queries,}
    return render_to_response('display.html',context,context_instance=RequestContext(request))
    
def filt_vid(request,queries):
    result = user_data.objects.filter(username__icontains=str(queries),videos__icontains = 'YES')
    form = sq()
    context = {'result':result,'form':form,'query':queries,}
    return render_to_response('display.html',context,context_instance=RequestContext(request))
def filt_sp(request,queries):    
    result = user_data.objects.filter(username__icontains=str(queries),staff_pick__icontains = 'YES')
    form = sq()
    context = {'result':result,'form':form,'query':queries,}
    return render_to_response('display.html',context,context_instance=RequestContext(request))

vim/templates/display.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
</head>  

	<body>	
	
		<div style = "float:left;margin-left:100px;margin-top:50px;">
		<form action = "/searching/" method = "POST">
		{% csrf_token %}
				<div class="fieldWrapper">	

					<label for="id_searq">  
				{{ form.searq }}

			<input src = "{{ STATIC_URL }}admin/img/search.png" type="image" alt="submit" value="Search" width="25" height="25" style = "float:left;margin-top:-27px;margin-left:156px;">	
		</label>
		<p style ="font-size:12px;font-style:ariana;color:black;"> (Type user name) </p>
		</div>
		
		</form>
		
		</div>
<div style = "display:inline;">
<a href = "/display">All</a>
<a href = "/pay/{{query}}">paying</a>
<a href = "/vid/{{query}}">videos</a>
<a href = "/sp/{{query}}">Staff Pick</a>


</div>



	
	<div style = "float:left;margin:70px 30px 35px 100px;">			

			<table border ="1" style = "width: 1100px;">
				<thead>
					<tr>
						<th style='width:80px;'>User Name</th>
						<th style='width:80px;'>URL</th>
						<th style='width:130px;'>Paid USer</th>
						<th style='width:200px;'>Videos</th>
						<th style='width:110px;'>Staff Pick</th>
						
					</tr>
				</thead>
				
				<tbody>
					{% for item in result %}

						<tr>
							<td style='width:80px;'>  {{ item.username|capfirst }} </a></td>
							<td> {{ item.url }} </td>
							<td> {{ item.payment }} </td>
							<td> {{ item.videos }} </td>
							<td> {{ item.staff_pick }} </td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	
		

		</body>
		</html>